-- Breno Augusto | RA: 24.01496-6
-- Bruno Nogueira | RA: 23.00313-8
-- Henrique Nalin | RA: 24.01883-0
-- Mateo Vuolo Cortez | RA: 24.00775-7
-- Mateusz Chaves Slawacki | RA: 24.01627-6
CREATE DATABASE dbdep;
USE dbdep;
CREATE TABLE DEPARTAMENTO(
idDepto INTEGER NOT NULL UNIQUE ,
nomeDepto VARCHAR(30) NOT NULL,
primary key(idDepto)
);
DESCRIBE DEPARTAMENTO;
INSERT INTO DEPARTAMENTO (idDepto, nomeDepto)
VALUES (10, 'Compras');
INSERT INTO DEPARTAMENTO (idDepto, nomeDepto)
VALUES (20, 'Engenharia');
INSERT INTO DEPARTAMENTO (idDepto, nomeDepto)
VALUES (40, 'Vendas');
INSERT INTO DEPARTAMENTO (idDepto, nomeDepto)
VALUES (55, 'Financeiro');
DESCRIBE DEPARTAMENTO;
CREATE TABLE FUNCIONARIO(
idFunc INTEGER NOT NULL,
nomeFunc CHAR(40) NOT NULL,
CPF CHAR(14) NOT NULL UNIQUE,
PRIMARY KEY (idFunc),
FOREIGN KEY (idDepto) REFERENCES DEPARTAMENTO (idDepto)
);
DESCRIBE FUNCIONARIO;
ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_FUNCIONARIO
FOREIGN KEY (IDDEPTO)
REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)
ON DELETE RESTRICT
ON UPDATE RESTRICT;
DESCRIBE FUNCIONARIO;
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME, CPF, IDDEPARTAMENTO)
VALUES
(3456, 'Paulo de Souza Alves', '345.987.123-98', 10),
(9872, 'Jose da Silva', '987.243.098-01', 10),
(1890, 'Pedro Rangel de Souza', '112.872.340-81', NULL),
(4680, 'Angela Silva Medeiros', '567.982.045-27', 40);
SELECT * FROM FUNCIONARIO;
DELETE FROM DEPARTAMENTO WHERE IDDEPARTAMENTO = 10;
-- Ao tentar excluir o departamento 10 com o comando DELETE FROM DEPARTAMENTO WHERE
IDDEPARTAMENTO = 10;,
a mensagem de erro que você pode receber é:
Não é possível excluir registro '10'; existem registros filhos referenciando-o na
tabela 'FUNCIONARIO'
Esse erro ocorre porque a exclusão de um departamento está violando a restrição de
integridade referencial.
ALTER TABLE FUNCIONARIO
MODIFY CONSTRAINT FK_FUNCIONARIO
ON DELETE SET NULL;
DELETE FROM DEPARTAMENTO WHERE IDDEPARTAMENTO = 10;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM FUNCIONARIO;
SELECT * FROM DEPARTAMENTO;
DROP TABLE DEPARTAMENTO;
SELECT * FROM FUNCIONARIO;
DROP TABLE FUNCIONARIO;
CREATE TABLE DEPARTAMENTO (
IDDEPARTAMENTO INT PRIMARY KEY,
NOME_DEPARTAMENTO VARCHAR(50) NOT NULL
);
CREATE TABLE FUNCIONARIO (
IDFUNCIONARIO INT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
CPF VARCHAR(11) NOT NULL,
IDDEPARTAMENTO INT NOT NULL,
FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)
);
INSERT INTO DEPARTAMENTO (idDepto, nomeDepto)
VALUES (10, 'Compras');
INSERT INTO DEPARTAMENTO (idDepto, nomeDepto)
VALUES (20, 'Engenharia');
INSERT INTO DEPARTAMENTO (idDepto, nomeDepto)
VALUES (40, 'Vendas');
INSERT INTO DEPARTAMENTO (idDepto, nomeDepto)
VALUES (55, 'Financeiro');
INSERT INTO FUNCIONARIO (IDFUNCIONARIO, NOME, CPF, IDDEPARTAMENTO)
VALUES
(3456, 'Paulo de Souza Alves', '345.987.123-98', 10),
(9872, 'Jose da Silva', '987.243.098-01', 10),
(1890, 'Pedro Rangel de Souza', '112.872.340-81', NULL),
(4680, 'Angela Silva Medeiros', '567.982.045-27', 40);
ALTER TABLE FUNCIONARIO
MODIFY CONSTRAINT FK_FUNCIONARIO
ON DELETE CASCADE;
DELETE FROM DEPARTAMENTO WHERE IDDEPARTAMENTO = 10;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM FUNCIONARIO;
SELECT D.NOME_DEPARTAMENTO, F.NOME, F.CPF
FROM DEPARTAMENTO AS D
INNER JOIN FUNCIONARIO AS F
ON D.IDDEPARTAMENTO = F.IDDEPARTAMENTO;